### PR TITLE
Add CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by jackey8616**
Add CONTRIBUTORS.md file #25

### CODE REVIEW

**Comment by danhenriquesc** [comment]
Hi @jackey8616 !

Thanks for your help,

I just merged a PR of @sbz 
Can you add his name on the list, and your name too (you are now a contributor :smile:) [In alphabetically order]?
Can you too add the title `Contributors` and a short comment like: `Sorted Alphabetically`?

**Comment by danhenriquesc** [comment]
Now, there is more contributors :smile: 
Can you reference the contributors.md file on readme?
Something like: List of contributors: link to file

**Comment by jackey8616** [comment]
@danhenriquesc  I can wait until you finished merge PRs.
and i will add everyone into Contributors with proper link to there file.
also a title with 'Contributors' and sort description as you suggested.

**Comment by danhenriquesc** [comment]
Nice!
Thank you soo much!

I gonna stop of review the PRs for some hours, so, I think that you can do the changes for now.
After we merge your PR, I will ask to new contributors to add its name it the list, and, if we need to someone to do a new update on the list, I open a new issue and you can do that on a new PR.

What do you think?

**Comment by jackey8616** [comment]
@danhenriquesc  check it out, if there is anything you want with Markdown. i do my best. 😃

**Comment by danhenriquesc** [comment]
That is great!
Just 2 adjustments:
1 - Your name should be before `sbz`, alphabetically
2 - Please, add the contributions section link to this file in README.me, before solutions.

**Comment by jackey8616** [comment]
I even not notice that i'm at wrong place..

**Comment by danhenriquesc** [comment]
Nice! Your changes are all ok!
But, I can't merge because there is some conflict (`This branch cannot be rebased due to conflicts`) and github don't me allow to do that until you solve the conflict.

Can you solve that?

**Comment by jackey8616** [comment]
@danhenriquesc  try it.

**Comment by jackey8616** [comment]
@danhenriquesc  I am idiot. 
The url of CONTRIBUTORS.md in README is wrong...
Can I fix it and directly push to this repo? 😢

**Pull request merged**
